name: Build and deploy ASP app to Azure Web App - digital-notice-board

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # ---------------- Backend (.NET Framework) ----------------
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore ./backend/YourSolution.sln

      - name: Build backend and publish
        run: msbuild ./backend/YourSolution.sln `
              /p:Configuration=Release `
              /p:DeployOnBuild=true `
              /p:WebPublishMethod=Package `
              /p:PackageAsSingleFile=true `
              /p:SkipInvalidConfigurations=true `
              /p:PackageLocation="${{ github.workspace }}\published\backend"

      # ---------------- Frontend (Node.js) ----------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'   # Use 20 LTS unless your package.json requires 22

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Copy frontend build to publish folder
        run: |
          mkdir "${{ github.workspace }}\published\frontend"
          xcopy /E /I /Y ".\frontend\build" "${{ github.workspace }}\published\frontend"

      # ---------------- Upload artifact ----------------
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ${{ github.workspace }}\published\**

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9C4151EDEBD94ADDB62BCDBF9A061974 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8DD072F030824368890854CCC324F067 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5BDF2D1A4A0048A2A640620A94E69060 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'digital-notice-board'
          slot-name: 'Production'
          package: .
